# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23b703485b8b2ca202079eadcc23677aba4da223d14d7d979625e4d51cdea8da5ebffe4b0694a3e0de24136296912e1266aebf5db83d405f642b5ce10f62707b

test:
  secret_key_base: da273c566b95e46304698bc86fb82ae1b9afd4dd22fbbfea9de488eb8dd8f7b6e770c5f4b596385f8ebe4c4cebee6c82c9de379f617b1ab4ea46d5713410fec8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
